<h1>Historia</h1>
<div id="walloftext">
	<p>S&aring;, vilka &auml;r vi d&aring;?</p>
  <p>Bra fr&aring;ga. XCoders bestod till en b&ouml;rjan (n&auml;r det begav sig, 2005 (ooh, back in the good 'ol days..)) av mig (Gustav Eklundh/R34p3r) och min k&auml;re v&auml;n Max Malm/benjick. Till designhj&auml;lp hade vi d&aring; Martin/Carthack, det var han som gjorde alla fancy bilder som fanns med i v&aring;ra scripts.</p>
	<p>Allt b&ouml;rjade med mig n&auml;r jag s&aring;g en forumpost p&aring; Fragbite om hur man anv&auml;nder CSS. Tidigare hade jag varit fast i tabelltr&auml;sket liksom m&aring;nga andra, men hade h&ouml;rt mycket trevliga saker om detta som man kallade &quot;CSS&quot;, och n&auml;r jag s&aring;g den artikeln blev resultatet d&aring;varande xcoders.info. Sidan var absolut inget m&auml;sterverk n&auml;r det kom till layout/design, faktiskt var den v&auml;ldigt ful. Fast det var inneh&aring;llet som gjorde den bra. Vi hade planer p&aring; att g&ouml;ra ett gratis administrationssystem f&ouml;r Counter-Strike-klaner sedan tidigare, men innan dess s&aring; publicerade vi (jag och benjick) ett antal artiklar/guider/introduktioner p&aring; &auml;mnena PHP, (X)HTML samt CSS. Detta f&ouml;r att det enligt oss inte fanns n&aring;gra direkta bra introduktioner p&aring; svenska till dessa &quot;spr&aring;k&quot;. Guiderna blev v&auml;ldigt uppskattade, och efter ett tag blev &auml;ven v&aring;rt administrationssystem &quot;klart&quot;.</p>
	<p>XAdmin v1 sl&auml;pptes med ganska stora f&ouml;rv&auml;ntningar fr&aring;n min sida. Jag ville g&ouml;ra n&aring;got stort och riktigt bra, men samtidigt simpelt att anv&auml;nda. Man skulle inte beh&ouml;va kunna PHP f&ouml;r att integrera systemet i sin hemsida, det skulle bara &quot;funka&quot;. Tyv&auml;rr s&aring; var mina kunskaper i PHP d&aring; ganska s&aring; begr&auml;nsade. Detta resulterade i en ganska kass strukturerad kod som i slut&auml;ndan gjorde systemet i princip om&ouml;jligt att underh&aring;lla (att folk &auml;nd&aring; orkade s&auml;tta sig in i det och faktiskt bygga p&aring;/om det &auml;r f&ouml;r mig ett under, credz till er!). Det i samband med svalnande intresse fr&aring;n min sida gjorde att projektet snart dog ut. Inte officiellt sett, men det h&auml;nde ingenting p&aring; ett antal &aring;r(!).</p>
	<p>Arbetet med XAdmin v2 kom ig&aring;ng n&aring;nstans kring 2006, d&aring; jag k&auml;nde att behovet f&ouml;r ett system likt XAdmin &auml;nd&aring; fanns d&auml;rute. Det och det faktum att (urs&auml;kta mig) idioter kunde kr&auml;nga hemsidor till intet ont anande CS-spelare f&ouml;r hutl&ouml;st mycket pengar gjorde att XAdmin &aring;terigen tog fart. Nu var tanken att systemet skulle byggas om helt fr&aring;n grunden, allt skulle vara nytt. Fler funktioner &auml;n tidigare och &auml;nnu l&auml;ttare att anv&auml;nda. Efter ett &quot;antal&quot; irriterande tabbar (tror jag skrev om det systemet som var i utveckling d&aring; tv&aring; eller tre g&aring;nger pga lite missar n&auml;r jag testade funktioner och liknande) s&aring; stagnerade utveckligen &auml;ven d&aring;.</p>
  <p>V&auml;ndpunkten blev nu i jul 2008, jag var uttr&aring;kad och beh&ouml;vde n&aring;got att g&ouml;ra, s&aring; jag best&auml;mde mig f&ouml;r att ge mig sj&auml;lv en utmaning. Kan jag skriva om ett helt nytt XAdmin p&aring; bara fyra dagar? Varf&ouml;r inte t&auml;nkte jag och best&auml;mde mig f&ouml;r att testa, om inte annat skulle jag ha kommit en bit p&aring; v&auml;gen efter fyra dagar. Detta var den 20e december, s&aring; fyra dagar var ett medvetet val, d&aring; tidigare projekt fr&aring;n oss som inte f&auml;rdigst&auml;llts var planerade till att sl&auml;ppas p&aring; julafton (lite nostalgi bara).</p>
	<p>Och nu, p&aring; natten mellan den 22a och 23e k&auml;nns det v&auml;ldigt sk&ouml;nt att sitta och skriva detta, som &auml;r det sista som faktiskt g&ouml;rs innan det nya XAdmin &auml;r klart f&ouml;r lansering. Fokus har nu legat p&aring; ett s&auml;kert, men &auml;nd&aring; l&auml;ttanv&auml;nt system som skall vara enkelt att implementera i en redan existerande sida, och jag personligen tror &auml;nd&aring; att vi &auml;r p&aring; r&auml;tt v&auml;g med de funktioner som erbjuds i den h&auml;r versionen av XAdmin. Tanken &auml;r att denna version av XAdmin ska f&aring; mogna till sig lite, f&ouml;r att sedan ocks&aring; ge sig ut p&aring; internationellt vatten n&auml;r alla sm&aring;fel som alltid uppst&aring;r i samband med en ny produkt &auml;r fixade.</p>
	<p>Har du l&auml;st s&aring; h&auml;r l&aring;ngt m&aring;ste jag &auml;nd&aring; passa p&aring; att ge dig en eloge, och om du har n&aring;gra fr&aring;gor eller &ouml;nskem&aring;l; tveka inte att kontakta mig p&aring; endera gustav[kanelbulle]xcoders.info eller ocks&aring; via IRC, d&auml;r n&aring;s jag p&aring; n&auml;tverket irc.eth0.info, under namnet R34p3r (f&ouml;rslagsvis i kanalen #dumfan).</p>
	<p>Happy fragging! </p>
</div>
